# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20160503_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
