# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20160616_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Index')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
    ]
