# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_index_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_Names',
            new_name='Index_History',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='indexes',
        ),
    ]
