# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20160622_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index_History',
            new_name='IndexHistory',
        ),
    ]
